name: Deploy Workshop Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-and-format:
    name: lint + format
    uses: ./.github/workflor/lint-and-format.yml

  version:
    name: Compute version
    uses: ./.github/workflows/versions
